export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL"
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';


// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";



// UPDATE USER INFO

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";


// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";


// SET SHOPPING CART
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";


// CREATE ORDER
export const BEGIN_ORDER_CREATE = 'BEGIN_ORDER_CREATE';
export const SUCCESS_ORDER_CREATE = 'SUCCESS_ORDER_CREATE';
export const FAIL_ORDER_CREATE = 'FAIL_ORDER_CREATE';
export const RESET_ORDER = 'RESET_ORDER';

// GET ORDER DETAIL
export const BEGIN_ORDER_DETAIL = 'BEGIN_ORDER_DETAIL';
export const SUCCESS_ORDER_DETAIL = 'SUCCESS_ORDER_DETAIL';
export const FAIL_ORDER_DETAIL = 'FAIL_ORDER_DETAIL';