export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL"
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';


// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";



// UPDATE USER INFO

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";